# Generated by Django 4.1.5 on 2023-02-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistika', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistika',
            name='narx',
            field=models.CharField(max_length=20),
        ),
    ]
