# Generated by Django 4.1.5 on 2023-02-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistika', '0002_alter_statistika_narx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistika',
            name='tolandi',
            field=models.CharField(max_length=20),
        ),
    ]
