# Generated by Django 4.1.5 on 2023-02-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistika', '0003_alter_statistika_tolandi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistika',
            name='qarz',
            field=models.CharField(max_length=20),
        ),
    ]
